export type Manual={id:string;title:string;summary:string;category:string;tags:string[];updatedAt:string;steps:string[];tip?:string};

export const manuals:Manual[]=[
  {id:"create-collection",title:"문서 취합 요청 만들기",summary:"대상자·마감·양식을 지정하고 공통 제출 링크를 만드는 방법",category:"문서 취합",tags:["요청","양식","링크","대상자"],updatedAt:"2026-08-24",steps:["문서 취합 화면에서 ‘새 취합 요청’을 누릅니다.","요청 제목, 안내 내용, 제출 마감을 입력합니다.","HWP 또는 HWPX 양식을 선택하고 제출 대상 교사를 체크합니다.","‘요청하기 및 링크 생성’을 누른 뒤 교사용 제출 링크만 대상자에게 전달합니다.","담당자 관리 링크는 비밀번호처럼 취급하고 외부에 전달하지 않습니다."],tip:"이름과 부서 자동입력이 필요하면 HWPX 양식에 {{교사명}}, {{부서명}}을 넣으세요."},
  {id:"draft-submit",title:"작성 중 임시저장하고 이어서 제출하기",summary:"작성 내용을 잃지 않도록 저장하고 같은 기기에서 이어 쓰는 방법",category:"문서 취합",tags:["임시저장","자동저장","복구","제출"],updatedAt:"2026-08-24",steps:["공통 링크에서 본인 이름과 부서를 정확히 선택합니다.","편집기가 열리면 기존 임시저장본이 있는지 자동으로 확인합니다.","작성 중에는 1분마다 자동저장되며, 중요한 시점에는 ‘임시저장’을 직접 누릅니다.","마지막 저장 시간이 화면에 표시됐는지 확인합니다.","작성이 끝나면 ‘작성 문서 제출’을 눌러 최종 버전으로 보관합니다."],tip:"임시저장본은 같은 브라우저의 복구 키로만 열립니다. 다른 기기에서는 자동 복구되지 않습니다."},
  {id:"manage-status",title:"제출·미제출 현황 확인하기",summary:"담당자 관리 링크에서 작성 중·제출 완료·재제출을 구분하는 방법",category:"문서 취합",tags:["현황","미제출","재제출","버전"],updatedAt:"2026-08-24",steps:["요청 생성 때 받은 담당자 관리 링크를 엽니다.","상단 숫자에서 전체 대상, 제출 완료, 작성 중, 미제출을 확인합니다.","교사별 행에서 최근 저장·제출 시간과 버전 수를 확인합니다.","다운로드를 펼쳐 필요한 제출 버전을 선택합니다.","재제출본이 있어도 이전 버전은 삭제되지 않습니다."]},
  {id:"rhwp-troubleshoot",title:"rHWP 편집기가 열리지 않을 때",summary:"빈 화면·로딩 실패·저장 오류가 발생했을 때 확인할 항목",category:"문제 해결",tags:["rHWP","한글","HWPX","오류","브라우저","안 열려요"],updatedAt:"2026-08-24",steps:["인터넷 시연 환경에서는 rHWP Studio 주소에 접속할 수 있는지 확인합니다.","페이지를 새로고침한 뒤 본인 이름을 다시 선택합니다.","HWP 대신 단순한 HWPX 양식으로 다시 시험합니다.","20MB를 넘거나 확장자가 다른 파일인지 확인합니다.","계속 실패하면 오류 문구와 사용한 브라우저를 담당자에게 전달합니다."],tip:"실제 폐쇄망 운영 전에는 rHWP Studio를 내부 서버에 자체 호스팅해야 합니다."},
  {id:"secure-files",title:"학교 문서를 안전하게 취급하는 기본 원칙",summary:"시험 단계와 실제 운영 단계에서 지켜야 할 최소 보안 수칙",category:"보안",tags:["보안","개인정보","내부망","관리 링크"],updatedAt:"2026-08-24",steps:["프로토타입에는 실제 학생·교직원 개인정보를 넣지 않습니다.","관리 링크는 메신저 단체방이나 외부 사람에게 전달하지 않습니다.","실제 운영 서버는 교내 허용 대역에서만 접속하도록 방화벽을 설정합니다.","파일 저장 폴더와 데이터베이스를 정기적으로 암호화 백업합니다.","운영 전 관리자 인증, 접근 기록, 보존·삭제 정책을 별도로 점검합니다."]},
  {id:"find-manual",title:"필요한 매뉴얼을 빠르게 찾는 방법",summary:"제목을 몰라도 업무 표현과 태그로 답을 찾는 검색 요령",category:"시스템 사용",tags:["검색","매뉴얼","태그","질문"],updatedAt:"2026-08-24",steps:["업무 매뉴얼 화면의 검색창에 하고 싶은 일을 입력합니다.","예: ‘재제출’, ‘임시저장’, ‘편집기 오류’처럼 실제 표현을 사용합니다.","필요하면 분야 버튼으로 결과를 좁힙니다.","결과 제목을 누르면 상세 절차가 바로 펼쳐집니다.","답을 찾지 못한 질문은 담당자에게 알려 다음 매뉴얼 항목으로 추가합니다."]},
];

export function filterManuals(items:Manual[],query:string,category:string){const keywords=query.trim().toLocaleLowerCase("ko").split(/\s+/).filter(Boolean);return items.filter(manual=>{const categoryMatch=category==="전체"||manual.category===category;const haystack=[manual.title,manual.summary,manual.category,...manual.tags,...manual.steps].join(" ").toLocaleLowerCase("ko");return categoryMatch&&keywords.every(keyword=>haystack.includes(keyword))})}
